### ISSUE TITLE
setSslEnabled(false) is not effective

### ISSUE THREAD

**Issue by xerial** [komamitsu/fluency#126]
```
new FluencyBuilderForFluentd().setSslEnabled(false)
```
Even if we add this config, Fluency (2.0.0 or 2.1.0) still tries to use SSL and produces unredable data for fluentd:
```
2019-03-10 11:08:40.804-0700  warn [RetryableSender] Sender failed to send data. sender=RetryableSender{baseSender=SSLSender{config=Config{host='127.0.0.1', port=63224, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='127.0.0.1', port=63224, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=null} org.komamitsu.fluency.fluentd.ingester.sender.SSLSender@8b1cbce, retryStrategy=ExponentialBackOffRetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}} RetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}}, isClosed=false} org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender@553de17d, retry=4
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.komamitsu.fluency.fluentd.ingester.sender.SSLSocketBuilder.build(SSLSocketBuilder.java:53)
	at org.komamitsu.fluency.fluentd.ingester.sender.SSLSender.getOrCreateSocketInternal(SSLSender.java:68)
	at org.komamitsu.fluency.fluentd.ingester.sender.SSLSender.getOrCreateSocketInternal(SSLSender.java:30)
	at org.komamitsu.fluency.fluentd.ingester.sender.NetworkSender.getOrCreateSocket(NetworkSender.java:75)
	at org.komamitsu.fluency.fluentd.ingester.sender.NetworkSender.sendInternal(NetworkSender.java:100)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendWithAck(FluentdSender.java:62)
	at org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender.sendInternal(RetryableSender.java:80)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendWithAck(FluentdSender.java:62)
	at org.komamitsu.fluency.fluentd.ingester.FluentdIngester.ingest(FluentdIngester.java:79)
	at org.komamitsu.fluency.buffer.Buffer.flushInternal(Buffer.java:358)
	at org.komamitsu.fluency.buffer.Buffer.flush(Buffer.java:112)
	at org.komamitsu.fluency.flusher.AsyncFlusher.lambda$new$0(AsyncFlusher.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)```

**Comment by xerial** [comment]
Sorry. It was not a bug of Fluency.
