### ISSUE TITLE
Some logs are lost after fluentd restart

### ISSUE THREAD

**Issue by thomasgermain** [komamitsu/fluency#172]
Hello,

we are integration your fluentd client. We are busing doing some tests.

We have a small spring boot app in which a fluency client is created. The fluency will send data to fluentd (and fluentd sends data to elasticsearch and data are available through kibana). The client is created with all defaults (expect for `errorHandler` and `fileBackupDir`).

Here is the problem:
1) Starting fluentd (and elasticsearch and kibana)
2) starting our spring boot app
4) send messages through fluentd -> this is working perfectly.
5) restarting (and waiting for) fluentd -> here comes trouble
6) sending  message 1 (~12kb) -> nothing sent to fluentd (even after thresholds) 
7) sending message 2 (~12kb) -> nothing sent to fluentd (even after thresholds) 
8) sending message 3 (~12kb) -> error, but at the end, message 3 is sent

logs of first and second messages after restart, everything seems to be fined, but nothing is actually going through the network.
```
2020-10-30 15:01:57.761 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.MultiSender      : send(): sender=TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=null, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144, isAvailable=true
2020-10-30 15:01:57.761 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.NetworkSender    : send(): sender.host=localhost, sender.port=9880, totalDataSize=11575
```
```
2020-10-30 15:03:42.400 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.MultiSender      : send(): sender=TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=null, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144, isAvailable=true
2020-10-30 15:03:42.400 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.NetworkSender    : send(): sender.host=localhost, sender.port=9880, totalDataSize=11575
``` 

logs of the 3rd message: it seems the socket "realize" that it's wrong and creating a new one. So there are some errors, but at the end, the message is sent.
```
2020-10-30 15:05:05.116 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.MultiSender      : send(): sender=TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=null, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144, isAvailable=true
2020-10-30 15:05:05.116 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.NetworkSender    : send(): sender.host=localhost, sender.port=9880, totalDataSize=11575
2020-10-30 15:05:05.117 ERROR 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.NetworkSender    : Failed to send 11575 bytes data
2020-10-30 15:05:05.131  WARN 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.MultiSender      : Failed to send: sender=TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=1604066705117, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144. Trying to use next sender...

java.io.IOException: An established connection was aborted by the software in your host machine
	at java.base/sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:58) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:182) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:514) ~[na:na]
	at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:507) ~[na:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.TCPSender.sendBuffers(TCPSender.java:86) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.TCPSender.sendBuffers(TCPSender.java:31) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.NetworkSender.sendInternal(NetworkSender.java:102) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.MultiSender.sendInternal(MultiSender.java:60) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender.sendInternal(RetryableSender.java:77) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.FluentdIngester.ingest(FluentdIngester.java:87) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flushInternal(Buffer.java:357) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flush(Buffer.java:112) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.flusher.Flusher.runLoop(Flusher.java:66) ~[fluency-core-2.4.1.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

2020-10-30 15:05:05.133  WARN 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.RetryableSender  : Sender failed to send data. sender=RetryableSender{baseSender=MultiSender{senders=[TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=1604066705117, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144]} org.komamitsu.fluency.fluentd.ingester.sender.MultiSender@133904ec, retryStrategy=ExponentialBackOffRetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}} RetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}}, isClosed=false} org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender@da59399, retry=0

org.komamitsu.fluency.fluentd.ingester.sender.MultiSender$AllNodesUnavailableException: All nodes are unavailable
	at org.komamitsu.fluency.fluentd.ingester.sender.MultiSender.sendInternal(MultiSender.java:72) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender.sendInternal(RetryableSender.java:77) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.FluentdIngester.ingest(FluentdIngester.java:87) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flushInternal(Buffer.java:357) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flush(Buffer.java:112) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.flusher.Flusher.runLoop(Flusher.java:66) ~[fluency-core-2.4.1.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

2020-10-30 15:05:05.497 TRACE 19620 --- [pool-2-thread-1] o.k.f.f.i.s.heartbeat.TCPHeartbeater     : TCPHeartbeat: remotePort=9880, localPort=63625
2020-10-30 15:05:05.543 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.MultiSender      : send(): sender=TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=1604066705117, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144, isAvailable=false
2020-10-30 15:05:05.544  WARN 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.RetryableSender  : Sender failed to send data. sender=RetryableSender{baseSender=MultiSender{senders=[TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=1604066705117, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144]} org.komamitsu.fluency.fluentd.ingester.sender.MultiSender@133904ec, retryStrategy=ExponentialBackOffRetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}} RetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}}, isClosed=false} org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender@da59399, retry=1

org.komamitsu.fluency.fluentd.ingester.sender.MultiSender$AllNodesUnavailableException: All nodes are unavailable
	at org.komamitsu.fluency.fluentd.ingester.sender.MultiSender.sendInternal(MultiSender.java:72) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender.sendInternal(RetryableSender.java:77) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.FluentdIngester.ingest(FluentdIngester.java:87) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flushInternal(Buffer.java:357) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flush(Buffer.java:112) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.flusher.Flusher.runLoop(Flusher.java:66) ~[fluency-core-2.4.1.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

2020-10-30 15:05:06.359 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.MultiSender      : send(): sender=TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=1604066705117, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144, isAvailable=false
2020-10-30 15:05:06.359  WARN 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.RetryableSender  : Sender failed to send data. sender=RetryableSender{baseSender=MultiSender{senders=[TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=1604066705117, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144]} org.komamitsu.fluency.fluentd.ingester.sender.MultiSender@133904ec, retryStrategy=ExponentialBackOffRetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}} RetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}}, isClosed=false} org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender@da59399, retry=2

org.komamitsu.fluency.fluentd.ingester.sender.MultiSender$AllNodesUnavailableException: All nodes are unavailable
	at org.komamitsu.fluency.fluentd.ingester.sender.MultiSender.sendInternal(MultiSender.java:72) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender.sendInternal(RetryableSender.java:77) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.FluentdIngester.ingest(FluentdIngester.java:87) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flushInternal(Buffer.java:357) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flush(Buffer.java:112) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.flusher.Flusher.runLoop(Flusher.java:66) ~[fluency-core-2.4.1.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

2020-10-30 15:05:06.495 TRACE 19620 --- [pool-2-thread-1] o.k.f.f.i.s.heartbeat.TCPHeartbeater     : TCPHeartbeat: remotePort=9880, localPort=63626
2020-10-30 15:05:07.498 TRACE 19620 --- [pool-2-thread-1] o.k.f.f.i.s.heartbeat.TCPHeartbeater     : TCPHeartbeat: remotePort=9880, localPort=63627
2020-10-30 15:05:07.961 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.MultiSender      : send(): sender=TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=1604066705117, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144, isAvailable=false
2020-10-30 15:05:07.961  WARN 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.RetryableSender  : Sender failed to send data. sender=RetryableSender{baseSender=MultiSender{senders=[TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=1604066705117, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144]} org.komamitsu.fluency.fluentd.ingester.sender.MultiSender@133904ec, retryStrategy=ExponentialBackOffRetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}} RetryStrategy{config=Config{baseIntervalMillis=400, maxIntervalMillis=30000} Config{maxRetryCount=7}}, isClosed=false} org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender@da59399, retry=3

org.komamitsu.fluency.fluentd.ingester.sender.MultiSender$AllNodesUnavailableException: All nodes are unavailable
	at org.komamitsu.fluency.fluentd.ingester.sender.MultiSender.sendInternal(MultiSender.java:72) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender.sendInternal(RetryableSender.java:77) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.fluentd.ingester.FluentdIngester.ingest(FluentdIngester.java:87) ~[fluency-fluentd-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flushInternal(Buffer.java:357) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.buffer.Buffer.flush(Buffer.java:112) ~[fluency-core-2.4.1.jar:na]
	at org.komamitsu.fluency.flusher.Flusher.runLoop(Flusher.java:66) ~[fluency-core-2.4.1.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

2020-10-30 15:05:08.497 TRACE 19620 --- [pool-2-thread-1] o.k.f.f.i.s.heartbeat.TCPHeartbeater     : TCPHeartbeat: remotePort=9880, localPort=63628
2020-10-30 15:05:09.484 TRACE 19620 --- [pool-2-thread-1] o.k.f.f.i.s.heartbeat.TCPHeartbeater     : TCPHeartbeat: remotePort=9880, localPort=63629
2020-10-30 15:05:10.484 TRACE 19620 --- [pool-2-thread-1] o.k.f.f.i.s.heartbeat.TCPHeartbeater     : TCPHeartbeat: remotePort=9880, localPort=63631
2020-10-30 15:05:11.175 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.MultiSender      : send(): sender=TCPSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='localhost', port=9880, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@90b795e} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@20ab7569, heartbeater=TCPHeartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}} Heartbeater{config=Config{host='localhost', port=9880, intervalMillis=1000}}, lastFailureTimestampMillis=null, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@3b712144, isAvailable=true
2020-10-30 15:05:11.175 TRACE 19620 --- [pool-3-thread-1] o.k.f.f.ingester.sender.NetworkSender    : send(): sender.host=localhost, sender.port=9880, totalDataSize=11575
```

The is an issue because message 1 and 2 are lost, while message 3 is resent.

Do you have any way to fix the issue ?

Thanks,

Thomas

**Comment by komamitsu** [comment]
Have you tried https://github.com/komamitsu/fluency#enable-ack-response-mode ?

**Comment by thomasgermain** [comment]
Yes we did, and it's working as expected. But using the ack response mode makes the sending synchronous and we have to support up to ~20MB log and for our use case, this is not acceptable to block the application during the sending.

**Comment by komamitsu** [comment]
In Fluency, buffered data is sent by a background thread, so it shouldn't block the application thread that calls `Fluency#emit`. But if you faced Fluency's buffer full because the throughput between Fluentd and Fluency didn't catch up with the ingestion throughput from application, the application could be blocked. In this case, it may be worth trying buffer configuration tuning.

From the view point of the throughput between Fluentd and Fluency, ACK response mode may affect the performance. But I think it's a kind of trade off between performance and durability.

**Comment by thomasgermain** [comment]
Well, actually I did a test again while ack mode is enabled and this is working async. I can't figure out how I concluded it was blocking 🤔 

Anyway,  I did some tests again while restarting fluentd and no message lost so far.

Thanks for your help !

Thomas
