### ISSUE TITLE
java.lang.NoClassDefFoundError: on Android 6 devices

### ISSUE THREAD

**Issue by tmeinhart** [komamitsu/fluency#231]
Hi, i'm faceing the following error only on Android 6 devices. 
```
java.lang.NoClassDefFoundError: org.komamitsu.fluency.validation.-$$Lambda$Validatable$ValidationList$3dXUFzTXYaDFnydovw7PMF63p0c
        at org.komamitsu.fluency.validation.Validatable$ValidationList.<clinit>(Validatable.java:51)
        at org.komamitsu.fluency.validation.Validatable$-CC.$default$validate(Validatable.java:119)
        at org.komamitsu.fluency.fluentd.ingester.sender.TCPSender$Config.validate(TCPSender.java)
        at org.komamitsu.fluency.fluentd.ingester.sender.TCPSender$Config.validateValues(TCPSender.java:120)
        at org.komamitsu.fluency.fluentd.ingester.sender.TCPSender.<init>(TCPSender.java:56)
        at org.komamitsu.fluency.fluentd.FluencyBuilderForFluentd.createBaseSender(FluencyBuilderForFluentd.java:209)
        at org.komamitsu.fluency.fluentd.FluencyBuilderForFluentd.createBaseSender(FluencyBuilderForFluentd.java:154)
        at org.komamitsu.fluency.fluentd.FluencyBuilderForFluentd.build(FluencyBuilderForFluentd.java:124)
        at ch.qos.logback.more.appenders.FluencyLogbackAppender.start(FluencyLogbackAppender.java:41)
...
```
At the moment i'm using the following dependencies:
```
implementation 'org.komamitsu:fluency-core:2.5.1'
implementation 'org.komamitsu:fluency-fluentd:2.5.1'
implementation 'com.sndyuk:logback-more-appenders:1.8.6'
```

Do you have an idea, what i'm missing here?

**Comment by komamitsu** [comment]
@tmeinhart How about trying Android's desugaring feature https://developer.android.com/studio/write/java8-support#library-desugaring ?
