### ISSUE TITLE
ClassNotFoundException: org.komamitsu.failuredetector.PhiAccuralFailureDetector$Builder

### ISSUE THREAD

**Issue by sanoyphilippe** [komamitsu/fluency#29]
Hi I tried to create a jar for this project. By cloning this and importing it through eclipse as a gradle project. Then exporting it as a jar file so that I could use it for my other projects.

I was going to test on how this was used but when I tried to instantiate Fluency using Fluency.defaultFluency method. It caused a ClassNotFoundException exception. Where exactly is the org.komamitsu.failuredetector located? Pardon if I might just have done something wrong. If I might have done something wrong in the creation of the jar, would it be alright if you could assist me in making a jar for your project?

**Comment by sanoyphilippe** [comment]
Below is the exception

Exception in thread "main" java.lang.NoClassDefFoundError: org/komamitsu/failuredetector/PhiAccuralFailureDetector$Builder
	at org.komamitsu.fluency.sender.failuredetect.PhiAccrualFailureDetectStrategy.<init>(PhiAccrualFailureDetectStrategy.java:12)
	at org.komamitsu.fluency.sender.failuredetect.PhiAccrualFailureDetectStrategy.<init>(PhiAccrualFailureDetectStrategy.java:9)
	at org.komamitsu.fluency.sender.failuredetect.PhiAccrualFailureDetectStrategy$Config.createInstance(PhiAccrualFailureDetectStrategy.java:60)
	at org.komamitsu.fluency.sender.failuredetect.FailureDetector.<init>(FailureDetector.java:39)
	at org.komamitsu.fluency.sender.MultiSender.<init>(MultiSender.java:34)
	at org.komamitsu.fluency.sender.MultiSender$Config.createInstance(MultiSender.java:163)
	at org.komamitsu.fluency.sender.MultiSender$Config.createInstance(MultiSender.java:1)
	at org.komamitsu.fluency.sender.RetryableSender.<init>(RetryableSender.java:43)
	at org.komamitsu.fluency.sender.RetryableSender$Config.createInstance(RetryableSender.java:125)
	at org.komamitsu.fluency.Fluency.buildDefaultFluency(Fluency.java:60)
	at org.komamitsu.fluency.Fluency.defaultFluency(Fluency.java:84)
	at jp.co.sharp.logmng.regist.service.impl.FluentD.main(FluentD.java:34)
Caused by: java.lang.ClassNotFoundException: org.komamitsu.failuredetector.PhiAccuralFailureDetector$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more

**Comment by sanoyphilippe** [comment]
@komamitsu

**Comment by komamitsu** [comment]
I guess you just imported a jar file of Fluency not bundled one with other dependent libraries. Why don't you use Gradle's dependencies management like this?
```
dependencies {
    compile 'org.komamitsu:fluency:0.0.11'
}
```

If you want to use Fluency as a jar file, we need to use something like maven shade plugin...
