### ISSUE TITLE
Broken Pipe error after 1 minute of idle

### ISSUE THREAD

**Issue by theDeniZ** [komamitsu/fluency#351]
Hello,
We are getting "Broken Pipe" errors whenever the logs are not being sent for 1+ minute. It is working fine, if the logs are sent with an interval less than a minute. 

Details:
Fluency Version: 2.6.0
Logback Version: 1.2.6
Logback Appenders Version: 1.8.6
TCP Connection to a FluentBit `forward` input:
```
[INPUT]
        Name              forward
        Listen            0.0.0.0
        Port              24284
        Buffer_Chunk_Size 20MB
        Buffer_Max_Size   1024MB
        Mem_Buf_Limit     1536MB
        storage.type      filesystem
```

For privacy reasons the host will be replaced with "0.0.0.0".

Error:

```
2021-12-01 09:34:17,701 ERROR [] [pool-154-thread-1] [TrackingId=] [org.komamitsu.fluency.fluentd.ingester.sender.NetworkSender] : Failed to send 5652 bytes data
2021-12-01 09:34:17,702 WARN  [] [pool-154-thread-1] [TrackingId=] [org.komamitsu.fluency.fluentd.ingester.sender.MultiSender] : Failed to send: sender=TCPSender{config=Config{host='0.0.0.0', port=9000, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}} NetworkSender{config=Config{host='0.0.0.0', port=9000, connectionTimeoutMilli=5000, readTimeoutMilli=5000, waitBeforeCloseMilli=1000} Config{senderErrorHandler=null}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@47a5ae90} org.komamitsu.fluency.fluentd.ingester.sender.failuredetect.PhiAccrualFailureDetectStrategy@6b76ab9c, heartbeater=TCPHeartbeater{config=Config{host='0.0.0.0', port=9000, intervalMillis=1000}} Heartbeater{config=Config{host='0.0.0.0', port=9000, intervalMillis=1000}}, lastFailureTimestampMillis=1638347657702, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.fluentd.ingester.sender.TCPSender@1b39a5d4. Trying to use next sender...
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:63)
	at sun.nio.ch.IOUtil.write(IOUtil.java:160)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:518)
	at java.nio.channels.SocketChannel.write(SocketChannel.java:513)
	at org.komamitsu.fluency.fluentd.ingester.sender.TCPSender.sendBuffers(TCPSender.java:86)
	at org.komamitsu.fluency.fluentd.ingester.sender.TCPSender.sendBuffers(TCPSender.java:31)
	at org.komamitsu.fluency.fluentd.ingester.sender.NetworkSender.sendInternal(NetworkSender.java:99)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56)
	at org.komamitsu.fluency.fluentd.ingester.sender.MultiSender.sendInternal(MultiSender.java:60)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56)
	at org.komamitsu.fluency.fluentd.ingester.sender.RetryableSender.sendInternal(RetryableSender.java:77)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.sendInternalWithRestoreBufferPositions(FluentdSender.java:74)
	at org.komamitsu.fluency.fluentd.ingester.sender.FluentdSender.send(FluentdSender.java:56)
	at org.komamitsu.fluency.fluentd.ingester.FluentdIngester.ingest(FluentdIngester.java:87)
	at org.komamitsu.fluency.buffer.Buffer.flushInternal(Buffer.java:357)
	at org.komamitsu.fluency.buffer.Buffer.flush(Buffer.java:112)
	at org.komamitsu.fluency.flusher.Flusher.runLoop(Flusher.java:67)
	at org.komamitsu.fluency.flusher.Flusher$$Lambda$127.000000008DB2E040.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:812)
```

How to reproduce:

Given the call.sh is a script which generates about 15 Log messages (about 4000 bytes)
Given the loop.sh is the following script:
```
./call.sh
./call.sh
./call.sh
./call.sh
./call.sh

sleep 61
./call.sh
./call.sh
./call.sh
```
When the loop.sh script is called and finished
Then the "Broken pipe" Error is seen in Logs
And not all generated logs are sent with Fluency Appender

Additional info: with a `sleep 45` the error is not found in logs.

The Logs are sent to a FluentBit remote server. Configuration:
```
<appender class="ch.qos.logback.more.appenders.FluencyLogbackAppender" name="FLUENCY">
    <encoder>
      <pattern>%msg</pattern>
    </encoder>
    <!-- Host name/address and port number which Fluentd placed -->
    <!-- DO NOT REMOVE SERVERS! When the first will break (broken pipe),-->
    <!-- next one will be used. May need only 2, may need all 6. -->
    <remoteServers>
      <remoteServer>
        <host>0.0.0.0</host>
        <port>9000</port>
      </remoteServer>
      <remoteServer>
        <host>0.0.0.0</host>
        <port>9000</port>
      </remoteServer>
      <remoteServer>
        <host>0.0.0.0</host>
        <port>9000</port>
      </remoteServer>
      <remoteServer>
        <host>0.0.0.0</host>
        <port>9000</port>
      </remoteServer>
      <remoteServer>
        <host>0.0.0.0</host>
        <port>9000</port>
      </remoteServer>
      <remoteServer>
        <host>0.0.0.0</host>
        <port>9000</port>
      </remoteServer>
    </remoteServers>

    <!-- Size is specified as 1MB * 1024 * 1024 = 1097152-->
    <maxBufferSize>5485760</maxBufferSize>
    <bufferChunkRetentionSize>1097152</bufferChunkRetentionSize>
    <bufferChunkInitialSize>524288</bufferChunkInitialSize>

    <tag>logback</tag>
    <useEventTime>true</useEventTime>

    <additionalField>
      <key>environment</key>
      <value>DEV</value>
    </additionalField>
    <additionalField>
      <key>module</key>
      <value>module1</value>
    </additionalField>

  </appender>
```

**Comment by komamitsu** [comment]
Looks like the TCP connection was disconnected for some reasons.

I have some questions.

1. The FluentBit input plugin listens port 24284. But FluencyLogbackAppender seems to connect port 9000. Is the configuration correct?
2. I guess `./call.sh` invokes a JVM process that uses Fluency. But all the JVM processes shouldn't affect each other. What is `call.sh` like?
3. I'm not sure this issue is caused by Fluency. We need to isolate the cause. Could you check how TCP connections to the FluentBit is disconnected using `tcpdump` or something? e.g. ` sudo tcpdump -i lo -vvv tcp port 24224`

**Comment by theDeniZ** [comment]
The answers following:

1. There is a Loadbalancer Kubernetes Service before the FluentBit, which listens on 9000 and forwards to any of 3 Pods of FluentBit to 24284
2. The call.sh is a simple curl call to a Resource, which generates some logs. There are 2 processes that can generate logs. The first generates them at a stable rate of minimum few log statements each second. The problem is in second process, which generates the logs one each 5-10 minutes. This logs are not getting sent with Fluency
3. I will check the tcpdump, thank you for the hint

**Comment by theDeniZ** [comment]
The Issue is resolved. The L4 Loadbalancer Service was not configured to leave connections open more than 50 seconds of time. Configuring the timeout in the service fixed the issue

Thank you for help
