### ISSUE TITLE
Use of EventTime result in errors

### ISSUE THREAD

**Issue by lrk** [komamitsu/fluency#82]
Hi,

I'm currently trying to figure out how to get log event with millisecond precision with fluentd.
I see that you offer this feature with the use of EventTime object as argument of emit() method.

I tried it but i get errors from fluent forward agent (from docker image https://hub.docker.com/r/fluent/fluentd/ latest version):

```
2017-11-30 20:45:11 +0000 [warn]: emit transaction failed: error_class=MessagePack::UnknownExtTypeError error="unexpected extension type" location="/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.41/lib/fluent/event.rb:149:in `feed_each'" tag="debug"
  2017-11-30 20:45:11 +0000 [warn]: suppressed same stacktrace
2017-11-30 20:45:11 +0000 [error]: forward error error=#<MessagePack::UnknownExtTypeError: unexpected extension type> error_class=MessagePack::UnknownExtTypeError
  2017-11-30 20:45:11 +0000 [error]: suppressed same stacktrace
2017-11-30 20:45:11 +0000 fluent.warn: {"error_class":"MessagePack::UnknownExtTypeError","error":"unexpected extension type","location":"/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.41/lib/fluent/event.rb:149:in `feed_each'","tag":"debug","message":"emit transaction failed: error_class=MessagePack::UnknownExtTypeError error=\"unexpected extension type\" location=\"/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.41/lib/fluent/event.rb:149:in `feed_each'\" tag=\"debug\""}
2017-11-30 20:45:11 +0000 fluent.error: {"error":"#<MessagePack::UnknownExtTypeError: unexpected extension type>","error_class":"MessagePack::UnknownExtTypeError","message":"forward error error=#<MessagePack::UnknownExtTypeError: unexpected extension type> error_class=MessagePack::UnknownExtTypeError"}
2017-11-30 20:45:11 +0000 [warn]: no patterns matched tag="fluent.error"
``` 

I'm using the version 1.6.0 and calling emit like this:
```
...
EventTime eventTime = EventTime.fromEpochMilli(System.currentTimeMillis());
fluency.emit(tag == null ? "" : tag, eventTime, data);
...
```

If i don't use EventTime, everything seem alright.

**Comment by lrk** [comment]
neverming, it work with the edge version or the container (0.14.x)
